name: Assign Ticket Number
on:
  pull_request:
    types: [opened]

jobs:
  assign-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Ticket Number
        id: assign
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.graphql(`
              query {
                repository(owner: "${{ github.repository_owner }}", name: "${{ github.repository }}") {
                  pullRequest(number: "${{ github.event.pull_request.number }}") {
                    title
                    body
                  }
                }
              }
            `);

            const pr = response.repository.pullRequest;
            const ticketNumber = extractTicketNumber(pr.title); // Fonction pour extraire le numéro du ticket du titre du PR

            if (ticketNumber) {
              console.log(`Ticket number found: ${ticketNumber}`);
              // Code pour attribuer le numéro de ticket au PR
            } else {
              console.log('No ticket number found in PR title');
            }

            function extractTicketNumber(title) {
              // Logique pour extraire le numéro du ticket du titre
            }
